version: "3.9"

services:
  db:
    image: postgres:16
    container_name: tryon-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: capslock
      POSTGRES_DB: tryon_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: ./backend
    container_name: tryon-api
    depends_on:
      - db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: capslock
      POSTGRES_DB: tryon_db
      POSTGRES_HOST: db
      POSTGRES_PORT: "5432"
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app

volumes:
  postgres_data:
